# Site settings
title: ROS精英训练营—RoboSchool
email: info@tonyrobotics.com
description: "ROS精英训练营—RoboSchool"
baseurl: "https://tonyrobotics.github.io"
url: "https://tonyrobotics.github.io"
github_username:  tonyrobotics

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

